// VibeSimulation App Version & Code Hash
// Auto-generated by stamp-version.mjs
// Do not edit manually - regenerate with: node stamp-version.mjs

window.APP_VERSION = "2025.08.28+hardening0";
window.APP_CODE_HASH = "sha256-index-bb9027c3.js-SRI-hash-placeholder";

// Note: APP_CODE_HASH should match the SRI integrity hash of your main bundle
// Run stamp-version.mjs to generate the correct hash from your built bundle
