#!/usr/bin/env node

/**
 * VibeSimulation Version Stamper
 * Generates app_version.js with current build info and SRI hash
 *
 * Usage:
 *   node stamp-version.mjs <bundle-path> <output-path> [version-suffix]
 *
 * Example:
 *   node stamp-version.mjs dist/index-bundle.js public/app_version.js "2025.08.28+build123"
 */

import { readFileSync, writeFileSync } from 'fs';
import { createHash } from 'crypto';
import { basename } from 'path';

function calculateSRI(filePath) {
  try {
    const content = readFileSync(filePath);
    const hash = createHash('sha256').update(content).digest('base64');
    const filename = basename(filePath);
    return `sha256-${hash}`;
  } catch (error) {
    console.warn(`Warning: Could not read ${filePath}, using placeholder`);
    return 'sha256-bundle-hash-placeholder';
  }
}

function generateVersionFile(bundlePath, outputPath, versionSuffix = '') {
  const now = new Date();
  const dateStr = now.toISOString().split('T')[0].replace(/-/g, '.');
  const version = versionSuffix || `${dateStr}+build${now.getTime()}`;

  const bundleHash = calculateSRI(bundlePath);
  const bundleName = basename(bundlePath);

  const content = `// VibeSimulation App Version & Code Hash
// Auto-generated by stamp-version.mjs on ${now.toISOString()}
// Bundle: ${bundleName}
// Do not edit manually - regenerate with: node stamp-version.mjs

window.APP_VERSION = "${version}";
window.APP_CODE_HASH = "${bundleHash}";

// Verification: This hash should match the SRI integrity attribute
// in your HTML when loading the bundle script
`;

  writeFileSync(outputPath, content, 'utf8');
  console.log(`✅ Generated ${outputPath}`);
  console.log(`   Version: ${version}`);
  console.log(`   Bundle: ${bundleName}`);
  console.log(`   Hash: ${bundleHash}`);

  return { version, bundleHash };
}

// CLI interface
if (import.meta.url === `file://${process.argv[1]}`) {
  const [,, bundlePath, outputPath, versionSuffix] = process.argv;

  if (!bundlePath || !outputPath) {
    console.error('Usage: node stamp-version.mjs <bundle-path> <output-path> [version-suffix]');
    console.error('Example: node stamp-version.mjs dist/index.js public/app_version.js "2025.08.28+build123"');
    process.exit(1);
  }

  try {
    generateVersionFile(bundlePath, outputPath, versionSuffix);
    console.log('🎉 Version stamping complete!');
  } catch (error) {
    console.error('❌ Error generating version file:', error.message);
    process.exit(1);
  }
}

export { generateVersionFile, calculateSRI };

