#created by edu.colorado.phet.buildtools.java.JavaBuildCommand
#Wed Aug 07 21:46:42 MDT 2013
project.flavor.battery-resistor-circuit.args=
project.name=battery-resistor-circuit
project.flavor.battery-resistor-circuit.title=Battery-Resistor Circuit
project.flavor.battery-resistor-circuit.mainclass=edu.colorado.phet.batteryresistorcircuit.BatteryResistorCircuitApplication
